app/urls.py
from django.urls import path,include
# from .views import views
from app.views import Register,khaltirequest,logout,subscribe,Home,end_sub,subscribed,subscription,signin,index,check_mail_ajax, Login,EsewaVerifyView,KhaltiVerifyView,RegisterViewSet,LoginViewSet,UserViewSet,PayHistoryViewSet,UserMembershipViewSet,MembershipViewSet,Subpayment,charge
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'register', RegisterViewSet)
router.register(r'login', LoginViewSet)
router.register(r'users', UserViewSet)
router.register(r'payhistory', PayHistoryViewSet)
router.register(r'usermembership', UserMembershipViewSet)
router.register(r'membership', MembershipViewSet)

urlpatterns = [
	path('', Home.as_view(), name='index'),
	path('login/', signin.as_view(), name='login'),
	path('home/', index, name='home'),
    path('logout/', logout, name='logout'),
    path('check-mail-ajax/',check_mail_ajax.as_view(), name='check_mail_ajax'),
    path('register/', Register.as_view(), name='register'),
    path('login-req', Login.as_view(), name='login_ajax'),
    path('esewa-verify/', EsewaVerifyView.as_view(), name="esewaverify"),
    path('subscription/', subscription.as_view(), name='subscription'),
    path('subscribe/', subscribe.as_view(), name='subscribe'),
    path('subscribed/',subscribed.as_view(), name='subscribed'),
    path('sub/', end_sub.as_view(), name='sub'),
    path("khalti-request/",khaltirequest.as_view(), name="khaltirequest"),
    #this is the url for verifying whether khalti payment is success or not
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
    path('api/', include(router.urls)),
    # for stripe payment
    path('subpayment/',Subpayment.as_view(),name="shopstripe"),
    path('chargeuser/<int:o_id>/',charge, name="chargeuser")

]

shop/urls.py
from django.urls.conf import include
from django.urls import path
from shop.views import CartProduct, KhaltiProductRequestView, KhaltiProductVerifyView,ProductViewSet,OrderViewSet,CartViewSet,HomePage,EsewaProductRequestView,EsewaProductVerifyView,KhaltiProductRequestView,KhaltiProductVerifyView, AddToCartView,MyCartView,ManageCartView,EmptyCartView,CheckoutView,get_filter_options,generate_color_palette,get_sales_chart,spend_per_customer_chart,payment_method_chart,payment_success_chart,statistics_view,payment,charge
from django.contrib.auth.decorators import login_required
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'products', ProductViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'carts', CartViewSet)

urlpatterns = [
     
    path('api',include(router.urls)),
    path('',login_required(HomePage.as_view()),name="home"),
    path("esewa-product-request/", login_required(EsewaProductRequestView.as_view()), name="esewarequest"),
    path("esewaproduct-verify/", login_required(EsewaProductVerifyView.as_view()), name="esewaproductverify"),
    path("khaltiproduct-request/", login_required(KhaltiProductRequestView.as_view()), name="khaltiproductrequest"),
     
    #this is the url for verifying whether khalti payment is success or not
    path("khaltiproduct-verify/", login_required(KhaltiProductVerifyView.as_view()), name="khaltiproductverify"),
    path("add-to-cart-<int:pro_id>/", login_required(AddToCartView.as_view()), name="addtocart"),
    path("my-cart/", login_required(MyCartView.as_view()), name="mycart"),
    path("manage-cart/<int:cp_id>/", login_required(ManageCartView.as_view()), name="managecart"),
    path("empty-cart/", login_required(EmptyCartView.as_view()), name="emptycart"),
    path("checkout/", login_required(CheckoutView.as_view()), name="checkout"),
    path('chart/filter-options/', get_filter_options, name='chart-filter-options'),
    path('chart/sales/<int:year>/', get_sales_chart, name='chart-sales'),
    path('chart/spend-per-customer/<int:year>/', spend_per_customer_chart, name='chart-spend-per-customer'),
    path('chart/payment-success/<int:year>/', payment_success_chart, name='chart-payment-success'),
    path('chart/payment-method/<int:year>/', payment_method_chart, name='chart-payment-method'),
    path('statistics/', statistics_view, name='shop-statistics'), 
    # this is for stripe payment
    path('payment/', payment.as_view(), name="payment"),
    path('charge/<int:o_id>/',charge,name='charge'),
]

subscription_django/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from dashboard.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('shop/', include('shop.urls')),
    path('dashboard/',index,name='index'),
     
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from app.models import User
from django.db.models import Sum, Count, Max
from django.template.defaultfilters import date
import datetime


# Create your models here.

# Product model
class Product(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="products",null=True,blank=True)
    description = models.TextField(max_length=300,null=True,blank=True)
    price = models.IntegerField()
    # payment_completed = models.BooleanField(default=False, null=True, blank=True)

# this is for the display the title in the admin panel
    def __str__(self):
        return self.title




class eSewa(models.Model):
	 merchant_id = models.CharField(max_length=100,default='epay_payment')

class Khalti(models.Model):
    public_key = models.CharField(max_length=150,blank=True,null=True)
    private_key = models.CharField(max_length=150,blank=True,null=True)
    
 

class Cart(models.Model):
    customer= models.OneToOneField(User, on_delete= models.SET_NULL,null=True, blank= True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add= True)

    def __str__(self):
        return "Cart:" + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, default=0)
    product= models.ForeignKey(Product, on_delete= models.CASCADE)
    rate = models.PositiveBigIntegerField()
    quantity = models.PositiveBigIntegerField()
    subtotal = models.PositiveBigIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + "CartProduct:" + str(self.id)

ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
("Cash On Delivery","Cash On Delivery"),
("Esewa","Esewa"),
("Khalti", "Khalti"),
("Stripe","Stripe")
)

class Order(models.Model):
    MONTHS = {1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'May', 6: 'Jun', 7: 'Jul', 8: 'Aug', 9: 'Sep', 10: 'Oct',
              11: 'Nov', 12: 'Dec'}

    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank= True)
    subtotal = models.PositiveBigIntegerField()
    discount = models.PositiveBigIntegerField()
    total = models.PositiveBigIntegerField()
    order_status = models.CharField(max_length=50, choices= ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add= True)
    payment_method = models.CharField(max_length=20,choices=METHOD,default="Cash On Delivery")
    payment_completed = models.BooleanField(default=False,null=True,blank=True)

    def __str__(self):
        return "Order Id:" + str(self.id)+", " +"Order by "+str(self.ordered_by)+", "+"payment_completed: "+str(self.payment_completed)

    # @classmethod
    # def total_info(cls):
    #     return cls.objects.aggregate(total_sales=Sum('total'), total_orders=Count('id'), peek_sale=Max('total'))

    # @classmethod
    # def best_month(cls):
    #     res = {}
    #     month_price = cls.objects.values_list('created_at__month').annotate(total=Sum('total'))
    #     if month_price:
    #         res['month'], res['total'] = max(month_price, key=lambda i: i[1])
    #         res['month_name'] = date(datetime.date(datetime.datetime.now().year, month=res['month'], day=1), 'F')
    #     return res

    # @classmethod
    # def orders_month_report(cls):
    #     now = datetime.datetime.now()

    #     month_val = now.month + 1

    #     # Limit the upper value
    #     if month_val > 12:
    #         month_val = 12
        
    #     filter_params = {
    #         'created_at__date__gte': '{year}-{month}-{day}'.format(year=now.year - 1, month=month_val,
    #                                                                  day=now.day),
    #         'created_at__date__lte': now.date()
    #     }

    #     annotate_params = {
    #         'total_order': Count('id'),
    #         'total_price': Sum('total')
    #     }

    #     queryset = cls.objects.filter(**filter_params).values('created_at__year', 'created_at__month').annotate(**annotate_params)

    #     return list(queryset), [cls.MONTHS[data.get('created_at__month')] for data in queryset]



 

shop/forms.py
from .models import Order
from django import forms

class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["ordered_by","shipping_address","mobile", "email",'payment_method']

shop/templates/change_list_graph.html
{% extends "admin/change_list.html" %}
{% load static %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            var ctx = document.getElementById("cart-chart");
            {% regroup cl.queryset|dictsort:"cart" by get_cart_display as cart_list %}
            var lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for cart in cart_list %}'{{ cart.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for cart in cart_list %}'{{ cart.list|length }}',{% endfor %}],
                        backgroundColor: [{% for cart in cart_list %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options: options
            });
            ctx = document.getElementById("ordered_by-chart");
            {% regroup cl.queryset|dictsort:"total" by grades as total_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for total in total_list %}'{{ total.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for total in total_list %}'{{ total.list|length }}',{% endfor %}],
                        backgroundColor: [{% for total in total_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
            ctx = document.getElementById("total-chart");
            {% regroup cl.queryset|dictsort:"payment_method" by get_language_display as payment_method_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for payment_method in payment_method_list %}'{{ payment_method.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for payment_method in payment_method_list %}'{{ payment_method.list|length }}',{% endfor %}],
                        backgroundColor: [{% for payment_method` in payment_method_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
        }
    </script>
{% endblock %}
{% block content %}
    <h1> Graphs </h1>
    <hr>
    <div class="row">
        <div class="col-sm-4">
            <canvas id="cart-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="ordered_by-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="payment_method-chart" style="width: 100px !important;"></canvas>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

shop/templates/statistic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Statistics</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-v4-grid-only@1.0.0/dist/bootstrap-grid.min.css">
  </head>
  <body>
    <div class="container">
      <form id="filterForm">
        <label for="year">Choose a year:</label>
        <select name="year" id="year"></select>
        <input type="submit" value="Load" name="_load">
      </form>
      <div class="row">
        <div class="col-6">
          <canvas id="salesChart"></canvas>
        </div>
        <div class="col-6">
          <canvas id="paymentSuccessChart"></canvas>
        </div>
        <div class="col-6">
          <canvas id="spendPerCustomerChart"></canvas>
        </div>
        <div class="col-6">
          <canvas id="paymentMethodChart"></canvas>
        </div>
      </div>
      <script>
        let salesCtx = document.getElementById("salesChart").getContext("2d");
        let salesChart = new Chart(salesCtx, {
          type: "bar",
          options: {
            responsive: true,
          }
        });
        let spendPerCustomerCtx = document.getElementById("spendPerCustomerChart").getContext("2d");
        let spendPerCustomerChart = new Chart(spendPerCustomerCtx, {
          type: "line",
          options: {
            responsive: true,
          }
        });
        let paymentSuccessCtx = document.getElementById("paymentSuccessChart").getContext("2d");
        let paymentSuccessChart = new Chart(paymentSuccessCtx, {
          type: "pie",
          options: {
            responsive: true,
            layout: {
              padding: {
                left: 0,
                right: 0,
                top: 0,
                bottom: 25
              }
            }
          }
        });
        let paymentMethodCtx = document.getElementById("paymentMethodChart").getContext("2d");
        let paymentMethodChart = new Chart(paymentMethodCtx, {
          type: "pie",
          options: {
            responsive: true,
            layout: {
              padding: {
                left: 0,
                right: 0,
                top: 0,
                bottom: 25
              }
            }
          }
        });
      </script>
      <script>
  $(document).ready(function() {
    $.ajax({
      url: "/shop/chart/filter-options/",
      type: "GET",
      dataType: "json",
      success: (jsonResponse) => {
        // Load all the options
        jsonResponse.options.forEach(option => {
          $("#year").append(new Option(option, option));
        });
        // Load data for the first option
        loadAllCharts($("#year").children().first().val());
      },
      error: () => console.log("Failed to fetch chart filter options!")
    });
  });

$("#filterForm").on("submit", (event) => {
  event.preventDefault();

  const year = $("#year").val();
  loadAllCharts(year)
});

function loadChart(chart, endpoint) {
  $.ajax({
    url: endpoint,
    type: "GET",
    dataType: "json",
    success: (jsonResponse) => {
      // Extract data from the response
      const title = jsonResponse.title;
      const labels = jsonResponse.data.labels;
      const datasets = jsonResponse.data.datasets;

      // Reset the current chart
      chart.data.datasets = [];
      chart.data.labels = [];

      // Load new data into the chart
      chart.options.title.text = title;
      chart.options.title.display = true;
      chart.data.labels = labels;
      datasets.forEach(dataset => {
        chart.data.datasets.push(dataset);
      });
      chart.update();
    },
    error: () => console.log("Failed to fetch chart data from " + endpoint + "!")
  });
}

function loadAllCharts(year) {
  loadChart(salesChart, `/shop/chart/sales/${year}/`);
  loadChart(spendPerCustomerChart, `/shop/chart/spend-per-customer/${year}/`);
  loadChart(paymentSuccessChart, `/shop/chart/payment-success/${year}/`);
  loadChart(paymentMethodChart, `/shop/chart/payment-method/${year}/`);
}
</script>
    </div>
  </body>
</html>
 