app/urls.py
from django.urls import path,include
# from .views import views
from app.views import Register,khaltirequest,logout,subscribe,Home,end_sub,subscribed,subscription,signin,index,check_mail_ajax, Login,EsewaVerifyView,KhaltiVerifyView,RegisterViewSet,LoginViewSet,UserViewSet,PayHistoryViewSet,UserMembershipViewSet,MembershipViewSet,Subpayment,charge
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'register', RegisterViewSet)
router.register(r'login', LoginViewSet)
router.register(r'users', UserViewSet)
router.register(r'payhistory', PayHistoryViewSet)
router.register(r'usermembership', UserMembershipViewSet)
router.register(r'membership', MembershipViewSet)

urlpatterns = [
	path('', Home.as_view(), name='index'),
	path('login/', signin.as_view(), name='login'),
	path('home/', index, name='home'),
    path('logout/', logout, name='logout'),
    path('check-mail-ajax/',check_mail_ajax.as_view(), name='check_mail_ajax'),
    path('register/', Register.as_view(), name='register'),
    path('login-req', Login.as_view(), name='login_ajax'),
    path('esewa-verify/', EsewaVerifyView.as_view(), name="esewaverify"),
    path('subscription/', subscription.as_view(), name='subscription'),
    path('subscribe/', subscribe.as_view(), name='subscribe'),
    path('subscribed/',subscribed.as_view(), name='subscribed'),
    path('sub/', end_sub.as_view(), name='sub'),
    path("khalti-request/",khaltirequest.as_view(), name="khaltirequest"),
    #this is the url for verifying whether khalti payment is success or not
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),
    path('api/', include(router.urls)),
    # for stripe payment
    path('subpayment/',Subpayment.as_view(),name="shopstripe"),
    path('chargeuser/<int:o_id>/',charge, name="chargeuser")

]

shop/urls.py
from django.urls.conf import include
from django.urls import path
from shop.views import CartProduct, KhaltiProductRequestView, KhaltiProductVerifyView,ProductViewSet,OrderViewSet,CartViewSet,HomePage,EsewaProductRequestView,EsewaProductVerifyView,KhaltiProductRequestView,KhaltiProductVerifyView, AddToCartView,MyCartView,ManageCartView,EmptyCartView,CheckoutView,get_filter_options,generate_color_palette,get_sales_chart,spend_per_customer_chart,payment_method_chart,payment_success_chart,statistics_view,payment,charge
from django.contrib.auth.decorators import login_required
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'products', ProductViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'carts', CartViewSet)

urlpatterns = [
     
    path('api',include(router.urls)),
    path('',login_required(HomePage.as_view()),name="home"),
    path("esewa-product-request/", login_required(EsewaProductRequestView.as_view()), name="esewarequest"),
    path("esewaproduct-verify/", login_required(EsewaProductVerifyView.as_view()), name="esewaproductverify"),
    path("khaltiproduct-request/", login_required(KhaltiProductRequestView.as_view()), name="khaltiproductrequest"),
     
    #this is the url for verifying whether khalti payment is success or not
    path("khaltiproduct-verify/", login_required(KhaltiProductVerifyView.as_view()), name="khaltiproductverify"),
    path("add-to-cart-<int:pro_id>/", login_required(AddToCartView.as_view()), name="addtocart"),
    path("my-cart/", login_required(MyCartView.as_view()), name="mycart"),
    path("manage-cart/<int:cp_id>/", login_required(ManageCartView.as_view()), name="managecart"),
    path("empty-cart/", login_required(EmptyCartView.as_view()), name="emptycart"),
    path("checkout/", login_required(CheckoutView.as_view()), name="checkout"),
    path('chart/filter-options/', get_filter_options, name='chart-filter-options'),
    path('chart/sales/<int:year>/', get_sales_chart, name='chart-sales'),
    path('chart/spend-per-customer/<int:year>/', spend_per_customer_chart, name='chart-spend-per-customer'),
    path('chart/payment-success/<int:year>/', payment_success_chart, name='chart-payment-success'),
    path('chart/payment-method/<int:year>/', payment_method_chart, name='chart-payment-method'),
    path('statistics/', statistics_view, name='shop-statistics'), 
    # this is for stripe payment
    path('payment/', payment.as_view(), name="payment"),
    path('charge/<int:o_id>/',charge,name='charge'),
]

subscription_django/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from dashboard.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('shop/', include('shop.urls')),
    path('dashboard/',index,name='index'),
     
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from app.models import User
from django.db.models import Sum, Count, Max
from django.template.defaultfilters import date
import datetime


# Create your models here.

# Product model
class Product(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="products",null=True,blank=True)
    description = models.TextField(max_length=300,null=True,blank=True)
    price = models.IntegerField()
    # payment_completed = models.BooleanField(default=False, null=True, blank=True)

# this is for the display the title in the admin panel
    def __str__(self):
        return self.title




class eSewa(models.Model):
	 merchant_id = models.CharField(max_length=100,default='epay_payment')

class Khalti(models.Model):
    public_key = models.CharField(max_length=150,blank=True,null=True)
    private_key = models.CharField(max_length=150,blank=True,null=True)
    
 

class Cart(models.Model):
    customer= models.OneToOneField(User, on_delete= models.SET_NULL,null=True, blank= True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add= True)

    def __str__(self):
        return "Cart:" + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, default=0)
    product= models.ForeignKey(Product, on_delete= models.CASCADE)
    rate = models.PositiveBigIntegerField()
    quantity = models.PositiveBigIntegerField()
    subtotal = models.PositiveBigIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + "CartProduct:" + str(self.id)

ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
("Cash On Delivery","Cash On Delivery"),
("Esewa","Esewa"),
("Khalti", "Khalti"),
("Stripe","Stripe")
)

class Order(models.Model):
    MONTHS = {1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'May', 6: 'Jun', 7: 'Jul', 8: 'Aug', 9: 'Sep', 10: 'Oct',
              11: 'Nov', 12: 'Dec'}

    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank= True)
    subtotal = models.PositiveBigIntegerField()
    discount = models.PositiveBigIntegerField()
    total = models.PositiveBigIntegerField()
    order_status = models.CharField(max_length=50, choices= ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add= True)
    payment_method = models.CharField(max_length=20,choices=METHOD,default="Cash On Delivery")
    payment_completed = models.BooleanField(default=False,null=True,blank=True)

    def __str__(self):
        return "Order Id:" + str(self.id)+", " +"Order by "+str(self.ordered_by)+", "+"payment_completed: "+str(self.payment_completed)

    # @classmethod
    # def total_info(cls):
    #     return cls.objects.aggregate(total_sales=Sum('total'), total_orders=Count('id'), peek_sale=Max('total'))

    # @classmethod
    # def best_month(cls):
    #     res = {}
    #     month_price = cls.objects.values_list('created_at__month').annotate(total=Sum('total'))
    #     if month_price:
    #         res['month'], res['total'] = max(month_price, key=lambda i: i[1])
    #         res['month_name'] = date(datetime.date(datetime.datetime.now().year, month=res['month'], day=1), 'F')
    #     return res

    # @classmethod
    # def orders_month_report(cls):
    #     now = datetime.datetime.now()

    #     month_val = now.month + 1

    #     # Limit the upper value
    #     if month_val > 12:
    #         month_val = 12
        
    #     filter_params = {
    #         'created_at__date__gte': '{year}-{month}-{day}'.format(year=now.year - 1, month=month_val,
    #                                                                  day=now.day),
    #         'created_at__date__lte': now.date()
    #     }

    #     annotate_params = {
    #         'total_order': Count('id'),
    #         'total_price': Sum('total')
    #     }

    #     queryset = cls.objects.filter(**filter_params).values('created_at__year', 'created_at__month').annotate(**annotate_params)

    #     return list(queryset), [cls.MONTHS[data.get('created_at__month')] for data in queryset]



 

shop/forms.py
from .models import Order
from django import forms

class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["ordered_by","shipping_address","mobile", "email",'payment_method']

shop/templates/shop/addtocart.html
{% extends 'shop/base.html' %}

{% block title %} 
    Add to cart
{% endblock title %}

{% block content %}
<div class="container">
    <h3>Product added to cart successfully </h3>
</div>
{% endblock content %}

shop/templates/shop/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

 <title>{% block title%} {% endblock %}</title>
  </head>
  <body>

  {% block content %}
  {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
 
 


   </body>
</html>

shop/templates/shop/checkout.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %} 
    Checkout
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Items in Cart</h3>
            <a href="{% url 'mycart' %}">UPDATE CART</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {%endfor%}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{ cart.total }}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-info"> Place Order</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

shop/templates/shop/dashboard_with_pivot.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard with Flexmonster</title>
    <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://cdn.flexmonster.com/demo.css">
    <style>
/* Charts Style  */

.fm-charts-color-1 {
  fill: #ffa600 !important;
}

.fm-charts-color-2 {
  fill: #7eae26 !important;
}

.fm-charts-color-3 {
  fill: #00a45a !important;
}

.fm-charts-color-4 {
  fill: #df3800 !important;
}

.fm-charts-color-5 {
  fill: #e95800 !important;
}

.fm-charts-color-6 {
  fill: #ffa600 !important;
}</style>
</head>
<body>
<div id="pivot-table-container" data-url="{% url 'pivot_data' %}"></div>
<div id="pivot-chart-container"></div>
<script>
function processData(dataset) {
    var result = []
    dataset = JSON.parse(dataset);
    dataset.forEach(item => result.push(item.fields));
    return result;
}
$.ajax({
    url: $("#pivot-table-container").attr("data-url"),
    dataType: 'json',
    success: function(data) {
        new Flexmonster({
            container: "#pivot-table-container",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 430,
            toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data),
                    mapping: {
                        "product": {
                            "caption": "Product"
                        },
                        "payment_method": {
                            "caption": "Payment Method"
                        },
                        "shipping_cost": {
                            "caption": "Shipping Cost",
                            "type": "number"
                        },
                        "unit_price": {
                            "caption": "Unit Price",
                            "type": "number"
                        }
                    }
                },
                "slice": {
                    "rows": [{
                        "uniqueName": "product_category"
                    }],
                    "columns": [{
                            "uniqueName": "payment_method"
                        },
                        {
                            "uniqueName": "[Measures]"
                        }
                    ],
                    "measures": [{
                            "uniqueName": "shipping_cost",
                            "aggregation": "sum"
                        },
                        {
                            "uniqueName": "unit_price",
                            "aggregation": "sum"
                        }
                    ]
                }
            }
        });
        new Flexmonster({
            container: "#pivot-chart-container",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 430,
            //toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data),
                    mapping: {
                        "product_category": {
                            "caption": "Product Category"
                        },
                        "payment_method": {
                            "caption": "Payment Method"
                        },
                        "shipping_cost": {
                            "caption": "Shipping Cost",
                            "type": "number"
                        },
                        "unit_price": {
                            "caption": "Unit Price",
                            "type": "number"
                        }
                    }
                },
                "slice": {
                    "rows": [{
                        "uniqueName": "product_category"
                    }],
                    "columns": [{
                        "uniqueName": "[Measures]"
                    }],
                    "measures": [{
                        "uniqueName": "Price",
                        "formula": "sum(\"shipping_cost\") + sum(\"unit_price\")",
                        "caption": "Price"
                    }]
                },
                "options": {
                    "viewType": "charts",
                    "chart": {
                        "type": "pie"
                    }
                }
            }
        });
    }
});


</script>
</body>
</html>

shop/templates/shop/esewarequest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Esewa Request</title>
    <style>
        #myform{
            display: none;
        }
    </style>
</head>
<body>
    <h3 style="text-align: center;">You will be redirected to the esewa website..</h3>
    <form action="https://uat.esewa.com.np/epay/main" method="POST" id="myform">
        <input value="{{order.total}}" name="tAmt" type="hidden">
        <input value="{{order.total}}" name="amt" type="hidden">
        <input value="0" name="txAmt" type="hidden">
        <input value="0" name="psc" type="hidden">
        <input value="0" name="pdc" type="hidden">
        <input value="{{esewa.merchant_id}}" name="scd" type="hidden">
        <input value="{{order.id}}" name="pid" type="hidden">
        <input value="http://127.0.0.1:8000/shop/esewaproduct-verify/" type="hidden" name="su">              
        <input value="{{request.build_absolute_uri}}" type="hidden" name="fu">                  
        <input value="Submit" type="submit">
    </form>

    {% comment %} this is the script for timeout {% endcomment %}
    <script>
        setTimeout(function(){
            document.getElementById("myform").submit()
        }, 500)
        
    </script>
</body>
</html>

shop/templates/shop/home.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>List page</title>
    <style>
    @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800&display=swap");

body {
    background-color: #eee;
    font-family: "Poppins", sans-serif
}
div { column-gap: 40px; }

.container {
    height: 100vh
}

.card {
    background-color: #fff;
    position: relative;
    width: 350px;
    border: none
}

.percent {
    width: 63px;
    height: 30px;
    position: absolute;
    background: red;
    color: #fff;
    border-radius: 3px;
    display: flex;
    justify-content: center;
    align-items: center;
    right: 0;
    border-bottom-left-radius: 15px;
    padding: 10px
}

.card-image {
    padding: 30px;
    display: flex;
    align-items: center;
    justify-content: center
}

.card-inner {
    padding: 20px;
    margin: auto;
}

.price span {
    color: orange;
    font-weight: 600;
    font-size: 20px
}

 

.details {
    border-radius: 20px;
    border-color: black;
    width: 150px;
    height: 40px;
    display: flex;
    justify-content: center;
    align-items: center
}

.success:hover {
  background-color: #04AA6D;
  color: white;

 
    </style>
  </head>
  <body>
  <div id="container">


  
 
  {% if user.is_authenticated %}
   
<div class="row">
  <div class="col-sm-12 mb-3">
    <h4 class="text-center">Welcome {{ user.username }}</h4>
  </div>
  <div class="col-sm-12 mt-2 text-center">
    <button class="btn btn-primary">
      <a href="{% url 'logout' %}" class="text-white">Logout</a>
    </button>
  </div>
</div>
  {% else %}
  <a href="{% url 'login' %}">login</a><br>
  {% endif %}
    <h1 style="text-align:center">our Products</h1>
    <hr>
    <br/>
    <br/>

{% comment %} {% for p in pro %}

<div class="card" style="width: 18rem;">
  <img src="{{p.image.url}}" class="card-img-top" alt="product_img">
  <div class="card-body">
    <h5 class="card-title">{{p.title}}</h5>
    <p class="card-text">{{p.description}} </p>
    <p class="card-text">${{p.price}} </p>
    <a href="{% url 'esewa' p.id %}" class="btn btn-primary">subscribe with esewa</a>
  </div>
</div>
 
   

    {% endfor %} {% endcomment %}


  
{% comment %} here we use forloop for the iteration  {% endcomment %}
 
 
 <div class="container d-flex justify-content-center align-items-center">
  <div class="row">
  {% for p in object_list %}
    <div class="card col-4"> 
   
    {% comment %} <span class="percent">-10%</span> {% endcomment %}
        <div class="card-image"> <img src="{{p.image.url}}" width="250"> </div>
        <div class="card-inner">
         {% comment %} <span>Groceries</span> {% endcomment %}
            <h5 class="mb-0">{{p.title}}</h5>
            <div class="price"> <span>Nrs {{p.price}}</span></sup> </div>
             {% comment %} <a href="{% url 'esewarequest' p.id %}" class="btn success text-uppercase btn-sm details">pay with esewa</a> {% endcomment %}
             <a href="{% url 'addtocart' p.id %}" class="btn success text-uppercase btn-sm details"> Add to Cart </a>
        </div>
        </div>
        <br>
        <br>
         {% endfor %}
    </div>
</div>
</div>
   

   



 
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    
    -->
  


  </body>
</html>

shop/templates/shop/khaltirequest.html
<html>
<head>
    <script src="https://unpkg.com/khalti-checkout-web@latest/dist/khalti-checkout.iffe.js"></script>
</head>
<body>
    
    <h3>Your order amount is Rs. {{order.total}}</h3>

    <!-- Place this where you need payment button -->
    <button id="payment-button">Pay with Khalti</button>
    <!-- Place this where you need payment button -->
    <!-- Paste this code anywhere in you body tag -->

    <a href="/">Go to Home page</a>

    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>        {# axios use garna ko lagi cdn link use gareko #}

    <script>
        var config = {
            // Keep your test_public_Key_
            "publicKey": "{{khalti.public_key}}",
            "productIdentity": "order_{{order.id}}",
            "productName": "order_{{order.id}}",
            "productUrl": "http://localhost:8000/",
            "paymentPreference": [
                "MOBILE_BANKING",
                "KHALTI",
                "EBANKING",
                "CONNECT_IPS",
                "SCT",
                ],
            "eventHandler": {
                onSuccess (payload) {
                    // hit merchant api for initiating verfication
                    console.log(payload)                        // khalti le pathayeko payload
                    
                    axios.get("/shop/khaltiproduct-verify/", {              // axios ko help batw ajax call gareko cha// hamro KhaltiVerifyView view ma get request pathako 
                        params: {
                            "token": payload.token,             // payload ma token huncha
                            "amount": payload.amount,           // payload ma amount huncha
                            "order_id": "{{order.id}}"
                        }
                    }).then(function(resp){                     // yaha response return vai rako huncha
                        if (resp.data.success == true)
                        {
                            alert("Thanks. Payment Completed Successfully")
                            location.href = "/"
                        }
                        else
                        {
                            alert("Sorry. Error occurred")
                            location.href = "{{request.build_absolute_uri}}"        // yo vaneko redirecting user to the current or same url
                        }
                    })
                },
                onError (error) {
                    console.log(error);
                },
                onClose () {
                    console.log('widget is closing');
                }
            }
        };

        var checkout = new KhaltiCheckout(config);
        var btn = document.getElementById("payment-button");
        btn.onclick = function () {
            // minimum transaction amount must be 10 NRs, i.e 1000 in paisa.
            
            checkout.show({amount: {{order.total}}*100 });
        }
    </script>
    <!-- Paste this code anywhere in you body tag -->
</body>
</html>

shop/templates/shop/mycart.html
{% extends 'shop/base.html' %}

{% block title %} 
    My Cart
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Items in my cart</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th> Rs. {{ cart.total }}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="{% url 'emptycart' %}">Empty Cart</a></th>
                        {% endif %}
                    </tr>
                    <tr>
                        <th>
                            {% if cart.cartproduct_set.all %}
                            <a class="btn btn-info" href="{% url 'checkout' %}">Checkout</a>
                            {% endif %}
                        </th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{%endblock content%}